CREATE TABLE IF NOT EXISTS hosts (
    id varchar(36) PRIMARY KEY,
    private_ip varchar(10) NOT NULL,
    public_ip varchar(10) NOT NULL,
    region int NOT NULL,
    provider int NOT NULL,
    status int NOT NULL,
    hash varchar(20) UNIQUE NOT NULL,
    fqdn varchar(50) NOT NULL,

    ram int NOT NULL,
    clock_speed int NOT NULL,
    cores int NOT NULL,
    storage int NOT NULL,
    cpu_limit int NOT NULL,
    ram_limit int NOT NULL,
    storage_limit int NOT NULL,
    capacity int NOT NULL,
    available_capacity int NOT NULL,
    organization_id varchar(36) NOT NULL,
    win_10 BOOL NOT NULL,
    win_8_1 BOOL NOT NULL,
    win_8 BOOL NOT NULL,
    win_7 BOOL NOT NULL,
    win_xp BOOL NOT NULL,
    mac_bigsur BOOL NOT NULL,
    mac_catalina BOOL NOT NULL,
    mac_mojave BOOL NOT NULL,
    mac_high_sierra BOOL NOT NULL,
    mac_sirra BOOL NOT NULL,
    mac_el_capitan BOOL NOT NULL,
    mac_yosemite BOOL NOT NULL,
    mac_mavericks BOOL NOT NULL,
    mac_mountain_lion BOOL NOT NULL,
    mac_lion BOOL NOT NULL,
    mobile_android_10 BOOL NOT NULL,
    mobile_android_9 BOOL NOT NULL,
    mobile_android_8 BOOL NOT NULL,
    mobile_android_7 BOOL NOT NULL,

    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);